### ISSUE TITLE
Pytorch3d import error on .so undefined symbol MemoryFormatEEE

### ISSUE THREAD

**Issue by yhyu13** [MoyGcc/vid2avatar#28]
Maybe it is a known issue, I am having trouble running  `python test.py`

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from v2a_model import V2AModel
  File "/home/hangyu5/Documents/Git-repoMy/AIResearchVault/repo/AIGC/game changer/vid2avatar/code/v2a_model.py", line 3, in <module>
    from lib.model.v2a import V2A
  File "/home/hangyu5/Documents/Git-repoMy/AIResearchVault/repo/AIGC/game changer/vid2avatar/code/lib/model/v2a.py", line 4, in <module>
    from .deformer import SMPLDeformer
  File "/home/hangyu5/Documents/Git-repoMy/AIResearchVault/repo/AIGC/game changer/vid2avatar/code/lib/model/deformer.py", line 4, in <module>
    from pytorch3d import ops
  File "/home/hangyu5/anaconda3/envs/v2a/lib/python3.7/site-packages/pytorch3d/ops/__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "/home/hangyu5/anaconda3/envs/v2a/lib/python3.7/site-packages/pytorch3d/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: /home/hangyu5/anaconda3/envs/v2a/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5emptyEN3c108ArrayRefIlEENS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE
```

However, I can import pytorch3d, but still fail at importing _C
```
Python 3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytorch3d import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libc10.so: cannot open shared object file: No such file or directory
>>> import pytorch3d
>>> 

```

Here is my package version list `pip list`

```
Package                        Version            Editable project location
------------------------------ ------------------ -----------------------------------------------------------------------------------------
absl-py                        1.4.0
aiohttp                        3.8.4
aiosignal                      1.3.1
aitviewer                      1.10.0
antlr4-python3-runtime         4.8
async-timeout                  4.0.2
asynctest                      0.13.0
attrs                          23.1.0
cachetools                     5.3.1
certifi                        2022.12.7
charset-normalizer             3.1.0
chumpy                         0.70
click                          8.1.3
cycler                         0.11.0
Cython                         0.29.35
docker-pycreds                 0.4.0
Flask                          2.0.3
fonttools                      4.38.0
frozenlist                     1.3.3
fsspec                         2023.1.0
future                         0.18.3
fvcore                         0.1.5.post20221221
gitdb                          4.0.10
GitPython                      3.1.31
glcontext                      2.3.7
google-auth                    2.20.0
google-auth-oauthlib           0.4.6
grpcio                         1.56.0
hydra-core                     1.1.1
idna                           3.4
imageio                        2.31.1
imgui                          2.0.0
importlib-metadata             6.7.0
importlib-resources            5.12.0
iopath                         0.1.10
itsdangerous                   2.1.2
Jinja2                         3.1.2
joblib                         1.2.0
kaolin                         0.13.0
kiwisolver                     1.4.4
Markdown                       3.4.3
MarkupSafe                     2.1.3
matplotlib                     3.5.3
moderngl                       5.8.2
moderngl-window                2.4.4
multidict                      6.0.4
multipledispatch               0.6.0
networkx                       2.6.3
numpy                          1.21.6
oauthlib                       3.2.2
omegaconf                      2.1.2
opencv-contrib-python-headless 4.7.0.72
packaging                      23.1
pathtools                      0.1.2
Pillow                         9.5.0
pip                            22.3.1
portalocker                    2.7.0
promise                        2.3
protobuf                       3.20.3
psutil                         5.9.5
pyasn1                         0.5.0
pyasn1-modules                 0.3.0
pyDeprecate                    0.3.1
pyglet                         2.0.8
pyparsing                      3.1.0
PyQt5                          5.15.9
PyQt5-Qt5                      5.15.2
PyQt5-sip                      12.12.1
pyrr                           0.10.3
python-dateutil                2.8.2
pytorch-lightning              1.5.7
pytorch3d                      0.7.4
PyWavelets                     1.3.0
PyYAML                         6.0
requests                       2.31.0
requests-oauthlib              1.3.1
roma                           1.3.2
rsa                            4.9
scikit-image                   0.18.1
scikit-video                   1.1.11
scipy                          1.7.3
sentry-sdk                     1.26.0
setproctitle                   1.3.2
setuptools                     59.5.0
shortuuid                      1.0.11
six                            1.16.0
smmap                          5.0.0
smplx                          0.1.28
tabulate                       0.9.0
tensorboard                    2.11.2
tensorboard-data-server        0.6.1
tensorboard-plugin-wit         1.8.1
termcolor                      2.3.0
tifffile                       2021.11.2
torch                          1.13.1+cu117
torchmetrics                   0.11.4
torchvision                    0.10.1+cu111
tornado                        6.1
tqdm                           4.65.0
trimesh                        3.22.1
typing_extensions              4.6.3
UNKNOWN                        0.0.0              /home/hangyu5/Documents/Git-repoMy/AIResearchVault/repo/AIGC/game changer/vid2avatar/code
urllib3                        1.26.16
usd-core                       22.5.post1
wandb                          0.13.1
websockets                     11.0.3
Werkzeug                       2.2.3
wheel                          0.38.4
yacs                           0.1.8
yarl                           1.9.2
zipp                           3.15.0

```

**Comment by MoyGcc** [comment]
There are some other users encountering the same issue: https://github.com/MoyGcc/vid2avatar/issues/13. Can you first try some ways suggested there and see how it works?
