### ISSUE TITLE
Can't reproduce results

### ISSUE THREAD

**Issue by Jerry-Master** [MoyGcc/vid2avatar#29]
When retraining from your pretrained checkpoint I start to get NaN in the in_shape_loss quite fast, after epoch 40 or so. I have repeated several times the process and always happens. When executing the testing code, not even a person shows up, it just a strange shape. Could you submit a way of perfectly reproducing your results without the need for training?

**Comment by Jerry-Master** [comment]
And if I move the pretrained checkpoint to the output folder and rename last so that it tricks the test module into using it, I get the following error:

`Error executing job with overrides: []
Traceback (most recent call last):
  File "test.py", line 36, in main
    trainer.test(model, testset, ckpt_path=checkpoint)
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 907, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 683, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 950, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1105, in _restore_modules_and_callbacks
    self.checkpoint_connector.restore_model()
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 168, in restore_model
    self.trainer.training_type_plugin.load_model_state_dict(self._loaded_checkpoint)
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 193, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/user/anaconda3/envs/vid2avatar/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for V2AModel:
	size mismatch for model.frame_latent_encoder.weight: copying a param with shape torch.Size([42, 32]) from checkpoint, the shape in current model is torch.Size([34, 32]).
	size mismatch for body_model_params.global_orient.weight: copying a param with shape torch.Size([42, 3]) from checkpoint, the shape in current model is torch.Size([34, 3]).
	size mismatch for body_model_params.transl.weight: copying a param with shape torch.Size([42, 3]) from checkpoint, the shape in current model is torch.Size([34, 3]).
	size mismatch for body_model_params.body_pose.weight: copying a param with shape torch.Size([42, 69]) from checkpoint, the shape in current model is torch.Size([34, 69]).
`

**Comment by MoyGcc** [comment]
Hi, I just figured it out. I don't know why but someone removed several original images from the google drive folder. Now I changed the access right to others and added the missing images. Could you try running the demo (training and test) again?

![image](https://github.com/MoyGcc/vid2avatar/assets/29098423/28900744-6055-4e3e-b688-858244f2d92e)

**Comment by interestingzhuo** [comment]
+1

**Comment by MoyGcc** [comment]
> +1

Can you maybe elaborate more about your issues?

**Comment by interestingzhuo** [comment]
> Owner

![image](https://github.com/MoyGcc/vid2avatar/assets/43921151/bbc6fbcd-ff51-4675-abee-4e5408d35e75)
all the loss become nan after 17 epoch

**Comment by MoyGcc** [comment]
I just tried to reproduce the error you have. But with the same training input, the loss will not become nan in my case. I think there is a similar problem as you have here https://github.com/MoyGcc/vid2avatar/issues/13 probably related to the GPU arch. It worth trying reinstalling pytorch that matches your CUDA version.

![image](https://github.com/MoyGcc/vid2avatar/assets/29098423/7e918deb-0e3b-48c6-a326-13c0a2cf349e)

**Comment by interestingzhuo** [comment]
> I just tried to reproduce the error you have. But with the same training input, the loss will not become nan in my case. I think there is a similar problem as you have here #13 probably related to the GPU arch. It worth trying reinstalling pytorch that matches your CUDA version.
> 
> ![image](https://user-images.githubusercontent.com/29098423/251077312-7e918deb-0e3b-48c6-a326-13c0a2cf349e.png)

It works!
