### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.distributed.algorithms.model_averaging'

### ISSUE THREAD

**Issue by japji313** [MoyGcc/vid2avatar#40]
firstly installed torch 1.9 
downgraded to 1.8 after seeing solutions on stack
Current :-
torch==1.8.1+cu111
torchaudio==0.8.1
torchmetrics==1.0.1
torchvision==0.9.1+cu111

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from v2a_model import V2AModel
  File "/home/prityush/Desktop/avatar/vid2avatar/code/v2a_model.py", line 1, in <module>
    import pytorch_lightning as pl
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 28, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 53, in <module>
    from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/trainer/__init__.py", line 17, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 58, in <module>
    from pytorch_lightning.loops import PredictionLoop, TrainingEpochLoop
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/loops/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.batch import TrainingBatchLoop  # noqa: F401
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/loops/batch/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.batch.training_batch_loop import TrainingBatchLoop  # noqa: F401
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 20, in <module>
    from pytorch_lightning.loops.optimization.manual_loop import _OUTPUTS_TYPE as _MANUAL_LOOP_OUTPUTS_TYPE
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.optimization.manual_loop import ManualOptimization  # noqa: F401
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/manual_loop.py", line 23, in <module>
    from pytorch_lightning.loops.utilities import _build_training_step_kwargs, _extract_hiddens
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 29, in <module>
    from pytorch_lightning.strategies.parallel import ParallelStrategy
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/strategies/__init__.py", line 15, in <module>
    from pytorch_lightning.strategies.bagua import BaguaStrategy  # noqa: F401
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/strategies/bagua.py", line 30, in <module>
    from pytorch_lightning.strategies.ddp import DDPStrategy
  File "/home/prityush/.pyenv/versions/vid_avatar/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 65, in <module>
    from torch.distributed.algorithms.model_averaging.averagers import ModelAverager
ModuleNotFoundError: No module named 'torch.distributed.algorithms.model_averaging'

**Comment by MoyGcc** [comment]
I don't see why a downgrade to Pytorch version 1.8 could solve any problem. You can refer to other similar issues like this one https://github.com/MoyGcc/vid2avatar/issues/29#issuecomment-1621236229.

**Comment by japji313** [comment]
with torch 1.10 and cuda 11.1 supported 
i get this issue tried many ways , still stuck on it help!!

 from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by bring-nirachornkul** [comment]
> with torch 1.10 and cuda 11.1 supported i get this issue tried many ways , still stuck on it help!!
> 
> from pytorch3d import _C ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

Same as mine.
Did you found the solution yet?
