### ISSUE TITLE
I can see the vis result using aitviewer,  but have OSError: [Errno 32] Broken pipe.  when i want to export the video.

### ISSUE THREAD

**Issue by ouusan** [MoyGcc/vid2avatar#48]
Hello!  
I can see the video in aitviewer, but failed to export it with following error. 
what is the problem and how can i solve it ? Thank you !

Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/home/ouusan/anaconda3/envs/vid2a/bin/imageformats" ...
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
loaded library "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
Rendering frames:   0%|          | 0/600 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/skvideo/io/abstract.py", line 514, in writeFrame
    self._proc.stdin.write(vid.tostring())
BrokenPipeError: [Errno 32] Broken Pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ouusan/vid2avatar/visualization/vis.py", line 52, in <module>
    vis_dynamic(args)
  File "/home/ouusan/vid2avatar/visualization/vis.py", line 32, in vis_dynamic
    viewer.run()
  File "/home/ouusan/vid2avatar/aitviewer/aitviewer/viewer.py", line 515, in run
    self.window.render(current_time, delta)
  File "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/moderngl_window/context/base/window.py", line 713, in render
    self.render_func(time, frame_time)
  File "/home/ouusan/vid2avatar/aitviewer/aitviewer/viewer.py", line 563, in render
    self.gui()
  File "/home/ouusan/vid2avatar/aitviewer/aitviewer/viewer.py", line 653, in gui
    gc()
  File "/home/ouusan/vid2avatar/aitviewer/aitviewer/viewer.py", line 857, in gui_menu
    self.gui_export()
  File "/home/ouusan/vid2avatar/aitviewer/aitviewer/viewer.py", line 1083, in gui_export
    quality=self.export_quality,
  File "/home/ouusan/vid2avatar/aitviewer/aitviewer/viewer.py", line 1760, in export_video
    writer.writeFrame(np.array(img))
  File "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/skvideo/io/abstract.py", line 519, in writeFrame
    raise IOError(msg)
OSError: [Errno 32] Broken Pipe

FFMPEG COMMAND:
/home/ouusan/anaconda3/envs/vid2a/bin/ffmpeg -y -framerate 60.0 -f rawvideo -pix_fmt rgb24 -s 1600x900 -i - -pix_fmt yuv420p -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 -r 60.0 -c:v libx264 -preset slow -profile:v high -level:v 4.0 -crf 23 /home/ouusan/vid2avatar/export/videos/aitviewer_0.mp4

FFMPEG STDERR OUTPUT:

QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so" 
QLibraryPrivate::unload succeeded on "/home/ouusan/anaconda3/envs/vid2a/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" 
QLibraryPrivate::unload succeeded on "Xcursor" (faked)

Process finished with exit code 1

**Comment by MoyGcc** [comment]
@kaufManu Sir, do you happen to know what the cause is?

**Comment by kaufManu** [comment]
To troubleshoot this further, can you please provide the following information:
- your OS
- version of aitviewer
- version of scikit-video package
- version of ffmpeg

Regards
Manuel
