### ISSUE TITLE
train.py not running

### ISSUE THREAD

**Issue by 2601705041** [MoyGcc/vid2avatar#62]
python train.py
Global seed set to 42
Working dir: /home/j222/vid2avatar-main/outputs/Video/parkinglot
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Error executing job with overrides: []
Traceback (most recent call last):
  File "train.py", line 33, in main
    model = V2AModel(opt)
  File "/home/j222/vid2avatar-main/code/v2a_model.py", line 30, in __init__
    self.model = V2A(opt.model, self.betas_path, self.gender, num_training_frames)
  File "/home/j222/vid2avatar-main/code/lib/model/v2a.py", line 38, in __init__
    self.deformer = SMPLDeformer(betas=betas, gender=self.gender)
  File "/home/j222/vid2avatar-main/code/lib/model/deformer.py", line 12, in __init__
    self.smpl = SMPLServer(gender=gender)
  File "/home/j222/vid2avatar-main/code/lib/model/smpl.py", line 44, in __init__
    output = self.forward(*torch.split(self.param_canonical, [1, 3, 72, 10], dim=1), absolute=True)
  File "/home/j222/vid2avatar-main/code/lib/model/smpl.py", line 77, in forward
    v_template=self.v_template)
  File "/home/j222/vid2avatar-main/code/lib/smpl/body_models.py", line 342, in forward
    self.lbs_weights, dtype=self.dtype,pose_blend=self.pose_blend)
  File "/home/j222/vid2avatar-main/code/lib/smpl/lbs.py", line 180, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/home/j222/vid2avatar-main/code/lib/smpl/lbs.py", line 272, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/home/j222/anaconda/envs/v2a/lib/python3.7/site-packages/torch/functional.py", line 325, in einsum
    return einsum(equation, *_operands)
  File "/home/j222/anaconda/envs/v2a/lib/python3.7/site-packages/torch/functional.py", line 327, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by 2601705041** [comment]
and here is something might wrong with hydra-core
print(hydra.utils.to_absolute_path('..'))  ------> /home/j222/vid2avatar-main/code/.. 
i think it should be /home/j222/vid2avatar-main

**Comment by 2601705041** [comment]
well now i get a new environment (cuda 11.1) use this:
pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

python train.py
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from v2a_model import V2AModel
  File "/home/j222/vid2avatar-main/code/v2a_model.py", line 3, in <module>
    from lib.model.v2a import V2A
  File "/home/j222/vid2avatar-main/code/lib/model/v2a.py", line 16, in <module>
    import kaolin
  File "/home/j222/vid2avatar-main/kaolin/kaolin/__init__.py", line 1, in <module>
    from . import io
  File "/home/j222/vid2avatar-main/kaolin/kaolin/io/__init__.py", line 5, in <module>
    from . import render
  File "/home/j222/vid2avatar-main/kaolin/kaolin/io/render.py", line 23, in <module>
    from ..render.camera import generate_perspective_projection
  File "/home/j222/vid2avatar-main/kaolin/kaolin/render/__init__.py", line 2, in <module>
    from . import mesh
  File "/home/j222/vid2avatar-main/kaolin/kaolin/render/mesh/__init__.py", line 1, in <module>
    from .utils import *
  File "/home/j222/vid2avatar-main/kaolin/kaolin/render/mesh/utils.py", line 22, in <module>
    from ... import ops
  File "/home/j222/vid2avatar-main/kaolin/kaolin/ops/__init__.py", line 1, in <module>
    from . import batch
  File "/home/j222/vid2avatar-main/kaolin/kaolin/ops/batch.py", line 17, in <module>
    from kaolin import _C
ImportError: /home/j222/vid2avatar-main/kaolin/kaolin/_C.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v
